# Generated by Django 5.1.1 on 2024-10-29 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0006_alter_artwork_category'),
        ('feedback', '0003_userbadge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artwork.artwork'),
        ),
    ]
