# Generated by Django 5.1.2 on 2024-10-28 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_image_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='favourites',
            name='priority',
            field=models.CharField(choices=[('High', 'Haute'), ('Medium', 'Moyenne'), ('Low', 'Basse')], default='Medium', max_length=10),
        ),
    ]
