# Generated by Django 5.1.2 on 2024-10-28 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_favourites_added_on_favourites_priority'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourites',
            unique_together=set(),
        ),
    ]
