# Generated by Django 4.1 on 2024-10-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_artwork_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(),
        ),
    ]
