# Generated by Django 5.1.1 on 2024-10-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('creation_date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='artworks/files/')),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
