# Generated by Django 5.1.1 on 2024-10-26 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_artwork_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artist',
        ),
    ]
