# Generated by Django 5.1.1 on 2024-10-26 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_remove_artwork_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='creation_date',
        ),
    ]
